# 服务器配置
server:
  servlet:
    context-path: /iw-bookkeeping
  port: 18004

# spring 配置
spring:
  application:
    name: iw-bookkeeping-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  config:
    import:
     - optional:nacos:iw-web
     - optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        enabled: true
      config:
        file-extension: yaml
      password: ${SPRING_CLOUD_NACOS_PASSWORD}
      username: ${SPRING_CLOUD_NACOS_USERNAME}
      server-addr: ${SPRING_CLOUD_NACOS_SERVER_ADDR}

# springdoc 配置
springdoc:
  swagger-ui:
    path: /doc.html
  packages-to-scan:
    - com.itwray.iw.bookkeeping.controller
