# 服务器配置
server:
  servlet:
    context-path: /iw-auth
  port: 18001

# spring 配置
spring:
  application:
    name: iw-auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        username: ${SPRING_CLOUD_NACOS_USERNAME}
        password: ${SPRING_CLOUD_NACOS_PASSWORD}

# springdoc 配置
springdoc:
  swagger-ui:
    path: /doc.html
  packages-to-scan:
    - com.itwray.iw.auth.controller