# 服务器配置
server:
  servlet:
    context-path: /iw-auth
  port: 18001

# spring 配置
spring:
  application:
    name: iw-auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iw_mixes
    username: iw_root
    password: iw@2024
  security:
    oauth2:
      client:
        registration:
          gigithub:
            client-id: client-id
            client-secret: client-secret
            redirect-uri: http://localhost:18001/iw-auth/login/oauth2/code/github
          google:
            redirect-uri: http://localhost:18001/iw-auth/login/oauth2/code/google
          dingtalk:
            provider: dingtalk
            authorization-grant-type: authorization_code
            client-id: client-id
            client-secret: client-secret
            redirect-uri: http://localhost:18001/iw-auth/login/oauth2/code/dingtalk
            scope: openid
            client-authentication-method: client_secret_post
        provider:
          dingtalk:
            authorization-uri: https://login.dingtalk.com/oauth2/auth
            token-uri: https://api.dingtalk.com/v1.0/oauth2/userAccessToken
            user-info-uri: https://api.dingtalk.com/v1.0/contact/users/me
            user-name-attribute: userid

# springdoc 配置
springdoc:
  swagger-ui:
    path: /doc.html
  packages-to-scan:
    - com.itwray.iw.auth.controller